Add Puppet8x support
voxpupuli/puppet-augeas pull request #97
Opened 2024-01-11 10:54 UTC by flepoutre

2024-02-16 09:38 UTC, tuxmea requested changes

2024-05-17 09:55 UTC, bastelfreak commented on manifests/init.pp
> -  if versioncmp($::puppetversion, '4.0.0') >= 0 {
I think we can remove the else block. We only support Puppet 7 and newer

2024-05-17 09:56 UTC, bastelfreak commented on manifests/lens.pp
> +  Optional[String] $stock_since  = undef,
I don't think we accept empty strings for any of those parameters? In that case please update it to `String[1]`

2024-05-17 09:56 UTC, bastelfreak commented on manifests/lens.pp
> +  if (!$stock_since or versioncmp($facts['augeasversion'], $stock_since) < 0) {
that's a deprecated fact. please use 
```suggestion
  if (!$stock_since or versioncmp($facts['augeas']['version'], $stock_since) < 0) {
```

2024-09-10 07:27 UTC, jhoblitt commented
Resolved by #99.

2024-09-10 07:27 UTC, closed without merging